// <auto-generated />
namespace WeDevelop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class imazh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(imazh));
        
        string IMigrationMetadata.Id
        {
            get { return "202105280511051_imazh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
